name: ProfilesPaperGui
version: 1.0.6
main: com.awooga.profiles.ProfilesPaperGuiPlugin
api-version: 1.13
depend: [PlaceholderAPI, ProfilesPaperCore]
commands:
  profiles:
    description: Main command to switch user profiles
    usage: /profiles